### ISSUE TITLE
Hi. Can you upload the code that generates ".csv"?

### ISSUE THREAD

**Issue by FriedaSmith** [HappyColor/SpeechFormer#2]
Hi. Can you upload the code that generates the `.csv`?

Note that you should create a metadata file (`.csv` format) for each dataset to record the `name` and `label` (and `state`, e.g. `train` or `dev` or `test`) of the samples. Then modify the argument: `meta_csv_file` in `./config/xxx_feature_config.json` according to the absolute path of the corresponding `.csv` file.

**Comment by HappyColor** [comment]
I apologize for the late reply. I have added the example `.csv` files in the `./metadata` directory.

**Comment by hvt1609** [comment]
Hi @HappyColor, I also looked at that example [metadata_daicwoz_crop_resample.csv](https://github.com/HappyColor/SpeechFormer/blob/master/metadata/metadata_daicwoz_crop_resample.csv) .csv. However, I still don't know how to generate it. 

For example,

>   | 303_s39_AUDIO.wav | 0 | 0 | train
>   | 303_s26_AUDIO.wav | 0 | 0 | train
>   | 303_s17_AUDIO.wav | 0 | 0 | train
>   | 303_s10_AUDIO.wav

`_s39_, _s26_, _s10_` what is your mean?

Similarly,

>   | 002-0-0 | Control | the scene is in the kitchen . | True
>   | 002-0-1 | Control | the mother is wiping dishes and the water is running on the floor . | True
>   | 002-0-2

Please add your code instead of.
Thank you for your work,

**Comment by HappyColor** [comment]
I apologize for the late reply. I'm sorry that my data processing was done a long time ago and I can't find the corresponding code now. To make up for this, I have detailed how each `.csv `file is generated and what they mean in the `./metadata` directory.
